"""Addendum AA analysis: AA0 validity gate, AA1 (D=0.5 image-only − native), AA2 (dose–response), AA3 (stale diagnostic).
Pooled statistics use a stratified item bootstrap (items resampled within each model). Output: real2_summary.md"""
import json
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
B = ROOT / 'outputs/tracking_algo_v1'
MODELS = ['qwen3vl8b', 'qwen3vl32b', 'qwen35_9b', 'internvl35_8b', 'llava_ov7b', 'gemma3_12b']
NB = 10000
rng = np.random.default_rng(20260928)


def boot(per_model, stat):
    """per_model: list of arrays (items x columns); stat maps the list to a scalar. Returns (value, lo, hi)."""
    v = stat(per_model)
    bs = [stat([a[rng.integers(0, len(a), len(a))] for a in per_model]) for _ in range(NB)]
    return v, float(np.quantile(bs, .025)), float(np.quantile(bs, .975))


def main():
    R = {m: [json.loads(l) for l in open(B / f'real2_{m}.jsonl')] for m in MODELS if (B / f'real2_{m}.jsonl').exists()}
    f = lambda t: f'{t[0]:+.3f} [{t[1]:+.3f}, {t[2]:+.3f}]'
    L = ['# Addendum AA (generated by scripts/tracking_algo_real2_stats.py)', '']
    for view in ('crop', 'wide'):
        L += [f'## view: {view}', '', '| model | img D=full (AA0) | img / native D=0.5 | img / native D=2 | img / native full | gap 0.5 | gap full | PCD-oracle 0.5 / full | PCD-det 0.5 |', '|' + '---|' * 9]
        inc, gaps = [], {}
        for m, recs in R.items():
            c = lambda dk, k: np.array([r[f'{view}_{dk}'][k] == r['gt'] for r in recs], float)
            ok = c('full', 'img').mean() >= 0.6
            if ok:
                inc.append(m)
            g = {dk: c(dk, 'img') - c(dk, 'native') for dk in ('0.5', '2', 'full')}
            gaps[m] = np.stack([g['0.5'], g['2'], g['full']], 1)
            pcd = (f"{c('0.5', 'pcd_oracle').mean():.2f} / {c('full', 'pcd_oracle').mean():.2f} | {c('0.5', 'pcd_det').mean():.2f}"
                   if view == 'crop' else '— | —')
            L.append(f"| {m}{'' if ok else ' (excluded)'} | {c('full', 'img').mean():.2f} | "
                     + ' | '.join(f"{c(dk, 'img').mean():.2f} / {c(dk, 'native').mean():.2f}" for dk in ('0.5', '2', 'full'))
                     + f" | {g['0.5'].mean():+.2f} | {g['full'].mean():+.2f} | {pcd} |")
        if inc:
            A = [gaps[m] for m in inc]
            aa1 = boot(A, lambda xs: float(np.mean([x[:, 0].mean() for x in xs])))
            aa2 = boot(A, lambda xs: float(np.mean([(x[:, 0] - x[:, 2]).mean() for x in xs])))
            d2 = boot(A, lambda xs: float(np.mean([x[:, 1].mean() for x in xs])))
            # AA3: on stale-option items at D=0.5, P(stale | native wrong) − P(stale | image-only wrong), pooled over errors
            S = []
            for m in inc:
                rows = []
                for r in R[m]:
                    if r['pen'] is None:
                        continue
                    x = r[f'{view}_0.5']
                    rows.append([x['native'] != r['gt'], x['native'] == r['pen'], x['img'] != r['gt'], x['img'] == r['pen']])
                S.append(np.array(rows, float))

            def aa3(xs):
                a = np.concatenate(xs)
                nw, iw = a[:, 0].sum(), a[:, 2].sum()
                return float(a[:, 1].sum() / max(nw, 1) - a[:, 3].sum() / max(iw, 1))
            a = np.concatenate(S)
            L += ['', f'Included (AA0): {inc}', '',
                  f'- **AA1** pooled image-only − native at D=0.5: {f(aa1)} (threshold ≥ 0.10)',
                  f'- D=2 pooled gap: {f(d2)}',
                  f'- **AA2** gap(D=0.5) − gap(full): {f(aa2)} (CI must exclude 0)',
                  f'- **AA3** P(stale | native wrong) − P(stale | img wrong) at D=0.5: {f(boot(S, aa3))}; '
                  f'native {int(a[:, 1].sum())}/{int(a[:, 0].sum())}, image-only {int(a[:, 3].sum())}/{int(a[:, 2].sum())}', '']
    (B / 'real2_summary.md').write_text('\n'.join(L))
    print('\n'.join(L))


if __name__ == '__main__':
    main()
