"""Addendum AG (revision 1) analysis: real vs rendered, held vs frozen vs image-only."""
import json
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
B = ROOT / 'outputs/tracking_algo_v1'
MODELS = ['qwen3vl8b', 'qwen3vl32b', 'qwen35_9b', 'internvl35_8b', 'llava_ov7b', 'gemma3_12b']
NB = 10000
rng = np.random.default_rng(20261003)
COLS = [(d, k, t) for t in ('gt', 'stale') for d in ('real', 'syn') for k in ('img', 'frozen', 'held')]


def rows(m, qn):
    return np.array([[r[qn][d][k] == r[qn][t] for d, k, t in COLS] for r in map(json.loads, open(B / f'real6_{m}.jsonl')) if qn in r], float)


def col(d, k, t='gt'):
    return COLS.index((d, k, t))


def boot(A, stat):
    v = stat(A)
    bs = [stat([a[rng.integers(0, len(a), len(a))] for a in A]) for _ in range(NB)]
    return v, float(np.quantile(bs, .025)), float(np.quantile(bs, .975))


def diff(i, j):
    return lambda A: float(np.mean([(a[:, i] - a[:, j]).mean() for a in A]))


def dom(A):
    return float(np.mean([((a[:, col('syn', 'frozen')] - a[:, col('syn', 'held')]) - (a[:, col('real', 'frozen')] - a[:, col('real', 'held')])).mean() for a in A]))


def main():
    ms = [m for m in MODELS if (B / f'real6_{m}.jsonl').exists()]
    f = lambda t: f'{t[0]:+.3f} [{t[1]:+.3f}, {t[2]:+.3f}]'
    L = ['# Addendum AG rev. 1 (generated by scripts/tracking_algo_real6_stats.py)', '', f'models: {ms}', '']
    for qn in ('pos', 'order'):
        A = [rows(m, qn) for m in ms]
        L += [f'## {qn} (n per model = {len(A[0])})', '', '| domain | image-only | frozen | held | frozen − held [95% CI] | P(stale) held − frozen [95% CI] | P(stale) img / frozen / held |', '|---|---|---|---|---|---|---|']
        for d in ('real', 'syn'):
            a = np.concatenate(A)
            L.append(f"| {d} | {a[:, col(d, 'img')].mean():.2f} | {a[:, col(d, 'frozen')].mean():.2f} | {a[:, col(d, 'held')].mean():.2f} | "
                     f"{f(boot(A, diff(col(d, 'frozen'), col(d, 'held'))))} | {f(boot(A, diff(col(d, 'held', 'stale'), col(d, 'frozen', 'stale'))))} | "
                     f"{a[:, col(d, 'img', 'stale')].mean():.2f} / {a[:, col(d, 'frozen', 'stale')].mean():.2f} / {a[:, col(d, 'held', 'stale')].mean():.2f} |")
        L += ['', f'- domain difference (syn − real) in frozen − held: {f(boot(A, dom))}', '',
              '| model | real img / frozen / held | real P(stale) frozen → held | syn img / frozen / held | syn P(stale) frozen → held |', '|---|---|---|---|---|']
        for m, a in zip(ms, A):
            g = lambda d, k, t='gt': a[:, col(d, k, t)].mean()
            L.append(f"| {m} | {g('real','img'):.2f} / {g('real','frozen'):.2f} / {g('real','held'):.2f} | {g('real','frozen','stale'):.2f} → {g('real','held','stale'):.2f} | "
                     f"{g('syn','img'):.2f} / {g('syn','frozen'):.2f} / {g('syn','held'):.2f} | {g('syn','frozen','stale'):.2f} → {g('syn','held','stale'):.2f} |")
        L.append('')
    (B / 'real6_summary.md').write_text('\n'.join(L) + '\n')
    print('\n'.join(L))


if __name__ == '__main__':
    main()
