"""Addendum X: evaluate PCD gates offline from the per-item logits saved by `tracking_algo_fix.py --dump`.
Output: outputs/tracking_algo_v1/gate_summary.{json,md}"""
import json
from pathlib import Path
import numpy as np
from scipy.stats import binomtest

ROOT = Path(__file__).resolve().parents[1]
B = ROOT / 'outputs/tracking_algo_v1'
MODELS = ['qwen3vl8b', 'qwen35_9b', 'internvl35_8b', 'llava_ov7b', 'gemma3_12b', 'idefics3_8b', 'internvl_gptoss']
STALE = ('chess_', 'M_', 'O_', 'U_chess')
CONTROL = ('N_',)


def rules(r):
    f, p, s = (np.array(r[k]) for k in ('lp_full', 'lp_past', 'lp_pres'))
    v = r['vals']
    past_on = bool(np.any(p != 0))
    out = {'native': v[int(f.argmax())], 'pcd': v[int((f - p).argmax())], 'present_clip': v[int(s.argmax())]}
    out['G_agree'] = out['pcd'] if past_on and p.argmax() == f.argmax() else out['native']
    c = np.sort(f - p)
    for d in (1.0, 0.5):   # G_margin (Addendum X amendment): G_agree plus a contrast margin of d nats
        out[f'G_margin{d}'] = out['G_agree'] if c[-1] - c[-2] >= d else out['native']
    return out


def mcnemar(a, b):
    a, b = np.asarray(a, bool), np.asarray(b, bool)
    n01, n10 = int((~a & b).sum()), int((a & ~b).sum())
    return 1.0 if n01 + n10 == 0 else float(binomtest(n10, n01 + n10, .5).pvalue)


def main():
    res, L = {}, ['# Addendum X: PCD gates (generated by scripts/tracking_algo_gate.py)', '']
    for m in MODELS:
        recs = []
        for suf in ('', '_U'):
            p = B / f'fix_dump_{m}{suf}.jsonl'
            if p.exists():
                recs += [json.loads(l) for l in open(p)]
        if not recs:
            continue
        for r in recs:
            r['pred'] = rules(r)
        names = ['native', 'pcd', 'G_agree', 'G_margin1.0', 'G_margin0.5', 'present_clip']
        cells = list(dict.fromkeys(r['cell'] for r in recs))
        acc = {c: {k: float(np.mean([r['pred'][k] == r['gt'] for r in recs if r['cell'] == c])) for k in names} for c in cells}
        stale = [c for c in cells if c.startswith(STALE)]
        gain = lambda k: float(np.mean([acc[c][k] - acc[c]['native'] for c in stale]))
        uc = [r for r in recs if r['cell'].startswith('U_chess')]
        x3 = (float(np.mean([r['pred']['G_agree'] == r['gt'] for r in uc])), float(np.mean([r['pred']['present_clip'] == r['gt'] for r in uc])),
              mcnemar([r['pred']['G_agree'] == r['gt'] for r in uc], [r['pred']['present_clip'] == r['gt'] for r in uc])) if uc else None
        res[m] = dict(acc=acc, pcd_gain=gain('pcd'), gate_gain=gain('G_agree'), margin_gain=gain('G_margin1.0'),
                      retention=(gain('G_agree') / gain('pcd')) if gain('pcd') > 0.05 else None,
                      x1_max_drop=max((acc[c]['native'] - acc[c]['G_agree'] for c in cells if c.startswith(CONTROL)), default=None),
                      x3_uchess=x3)
        R = res[m]
        ret = '' if R['retention'] is None else f", retention {R['retention']:.2f}"
        u = 'n/a' if x3 is None else f'{x3[0]:.2f} vs {x3[1]:.2f}, p={x3[2]:.2g}'
        L += [f'## {m}', '', f"stale-cell mean gain over native: PCD {R['pcd_gain']:+.3f}, G_agree {R['gate_gain']:+.3f}{ret}; "
              f"control max drop (native − G_agree) {R['x1_max_drop']}; U-chess G_agree vs present-clip {u}", '',
              '| cell | ' + ' | '.join(names) + ' |', '|---' * (len(names) + 1) + '|']
        L += [f'| {c} | ' + ' | '.join(f'{acc[c][k]:.2f}' for k in names) + ' |' for c in cells]
        L.append('')
    (B / 'gate_summary.json').write_text(json.dumps(res, indent=1))
    (B / 'gate_summary.md').write_text('\n'.join(L))
    print('\n'.join(L))


if __name__ == '__main__':
    main()
