#!/usr/bin/env python3
"""Addendum AH summary: accuracy and P(stale) per masking condition, McNemar vs none, sanity agreement with AG held."""
from pathlib import Path
import json
import sys

import numpy as np
from scipy.stats import binomtest

ROOT = Path(__file__).resolve().parents[1]
B = ROOT / 'outputs/tracking_algo_v1'
MODELS = ['qwen3vl8b', 'llava_ov7b', 'gemma3_12b']


def mcnemar(a, b):
    n01, n10 = int(np.sum(a & ~b)), int(np.sum(~a & b))
    return n01, n10, (binomtest(n01, n01 + n10).pvalue if n01 + n10 else 1.0)


def main():
    L = ['# Addendum AH (generated by scripts/tracking_algo_real7_stats.py)', '',
         'Position questions, AG rev. 1 held clips. Masks block text positions from the prior-state (or final) frames in the listed layers.', '']
    for m in MODELS:
        p = B / f'real7_{m}.jsonl'
        if not p.exists():
            continue
        R = [json.loads(l) for l in open(p)]
        ag = {r['id']: r['pos'] for r in map(json.loads, open(B / f'real6_{m}.jsonl'))}
        L += [f'## {m} (n = {len(R)})', '']
        for dom in ('real', 'syn'):
            agree = np.mean([r[dom]['none'] == ag[r['id']][dom]['held'] for r in R])
            L += [f'### {dom}  (sanity: none vs AG held agreement {agree:.3f})', '',
                  '| condition | accuracy | P(stale) | stale none→cond (lost:gained), McNemar p | correct (gained:lost), p |', '|---|---|---|---|---|']
            st0 = np.array([r[dom]['none'] == r['stale'] for r in R]); ac0 = np.array([r[dom]['none'] == r['gt'] for r in R])
            for c in R[0][dom]:
                st = np.array([r[dom][c] == r['stale'] for r in R]); ac = np.array([r[dom][c] == r['gt'] for r in R])
                s01, s10, sp = mcnemar(st0, st); a01, a10, apv = mcnemar(ac, ac0)
                L.append(f'| {c} | {ac.mean():.3f} | {st.mean():.3f} | {s01}:{s10}, p={sp:.3g} | {a01}:{a10}, p={apv:.3g} |')
            L.append('')
    out = '\n'.join(L)
    (B / 'real7_summary.md').write_text(out + '\n')
    print(out)


if __name__ == '__main__':
    sys.exit(main())
