"""Addendum AD analysis: image-only − native per cell and main effects of m, fps, dur (pooled over models, item bootstrap per model)."""
import itertools
import json
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
B = ROOT / 'outputs/tracking_algo_v1'
MODELS = ['qwen3vl8b', 'qwen3vl32b', 'qwen35_9b', 'internvl35_8b', 'llava_ov7b', 'gemma3_12b']
CELLS = list(itertools.product((1, 4), (2, 4), (1, 4)))
NB = 10000
rng = np.random.default_rng(20261002)


def arr(R, qn):
    """items x cells x (gap, P(stale) native − P(stale) img)."""
    out = []
    for r in R:
        row = []
        for m, fps, dur in CELLS:
            q = r[f'm{m}_{qn}']; c = q[f'fps{fps}_dur{dur}']
            row.append([(q['img'] == q['gt']) - (c == q['gt']), (c == q['stale']) - (q['img'] == q['stale'])])
        out.append(row)
    return np.array(out, float)


def boot(A, stat):
    v = stat(A)
    bs = [stat([a[rng.integers(0, len(a), len(a))] for a in A]) for _ in range(NB)]
    return v, float(np.quantile(bs, .025)), float(np.quantile(bs, .975))


def effect(idx, k=0):
    lo = [i for i, c in enumerate(CELLS) if c[idx] == min(x[idx] for x in CELLS)]
    hi = [i for i, c in enumerate(CELLS) if c[idx] == max(x[idx] for x in CELLS)]
    return lambda A: float(np.mean([a[:, hi, k].mean() - a[:, lo, k].mean() for a in A]))


def main():
    ms = [m for m in MODELS if (B / f'synthword2_{m}.jsonl').exists()]
    f = lambda t: f'{t[0]:+.3f} [{t[1]:+.3f}, {t[2]:+.3f}]'
    L = ['# Addendum AD (generated by scripts/tracking_algo_synthword2_stats.py)', '', f'models: {ms}', '']
    for qn in ('pos', 'order'):
        A = {m: arr([json.loads(l) for l in open(B / f'synthword2_{m}.jsonl')], qn) for m in ms}
        L += [f'## {qn}: image-only − native per cell', '', '| model | ' + ' | '.join(f'm{c[0]} fps{c[1]} dur{c[2]}' for c in CELLS) + ' |', '|---' * (len(CELLS) + 1) + '|']
        for m, a in A.items():
            L.append(f'| {m} (n={len(a)}) | ' + ' | '.join(f'{x:+.2f}' for x in a[:, :, 0].mean(0)) + ' |')
        L.append('| pooled | ' + ' | '.join(f'{x:+.2f}' for x in np.mean([a[:, :, 0].mean(0) for a in A.values()], 0)) + ' |')
        L += ['', '| main effect (high − low) | on gap [95% CI] | on P(stale) native − img [95% CI] |', '|---|---|---|']
        for name, i in (('m 1→4', 0), ('fps 2→4', 1), ('dur 1→4 s', 2)):
            L.append(f'| {name} | {f(boot(list(A.values()), effect(i)))} | {f(boot(list(A.values()), effect(i, 1)))} |')
        L.append('')
    (B / 'synthword2_summary.md').write_text('\n'.join(L) + '\n')
    print('\n'.join(L))


if __name__ == '__main__':
    main()
