"""Addendum AE analysis: AE1 (image-only − native at D=0.5), AE2 (penultimate share of errors), and exploratory splits
by the number of changes and by how long the penultimate arrangement stayed (from the 1-fps box states)."""
import json
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
B = ROOT / 'outputs/tracking_algo_v1'
MODELS = ['qwen3vl8b', 'qwen3vl32b', 'qwen35_9b', 'internvl35_8b', 'llava_ov7b', 'gemma3_12b']
NB = 10000
rng = np.random.default_rng(20260930)


def pen_duration(r):
    """Seconds the penultimate arrangement was held (next state's first frame minus its first frame, 30 fps)."""
    st = r['states']; fin = st[-1][1]
    i = max(j for j, (f, w) in enumerate(st) if w != fin)
    return (st[i + 1][0] - st[i][0]) / 30


def rows(R, qn, dk, sel=lambda r: True):
    return np.array([[x[qn][dk][0] == x[qn]['gt'], x[qn][dk][1] == x[qn]['gt'], x[qn][dk][0] == x[qn]['stale'], x[qn][dk][1] == x[qn]['stale']]
                     for x in R if qn in x and sel(x)], float).reshape(-1, 4)


def boot(A, stat):
    v = stat(A)
    bs = [stat([a[rng.integers(0, len(a), len(a))] for a in A]) for _ in range(NB)]
    return v, float(np.quantile(bs, .025)), float(np.quantile(bs, .975))


gap = lambda A: float(np.mean([(a[:, 0] - a[:, 1]).mean() for a in A if len(a)]))


def pen_err(A):
    a = np.concatenate(A); nw, iw = 1 - a[:, 1], 1 - a[:, 0]
    return float((a[:, 3] * nw).sum() / max(nw.sum(), 1) - (a[:, 2] * iw).sum() / max(iw.sum(), 1))


def main():
    R = {m: [json.loads(l) for l in open(B / f'real4_{m}.jsonl')] for m in MODELS if (B / f'real4_{m}.jsonl').exists()}
    f = lambda t: f'{t[0]:+.3f} [{t[1]:+.3f}, {t[2]:+.3f}]'
    L = ['# Addendum AE (generated by scripts/tracking_algo_real4_stats.py)', '', f'models: {list(R)}', '']
    splits = {'all': lambda r: True, '<=2 changes': lambda r: r['n_changes'] <= 2, '>=3 changes': lambda r: r['n_changes'] >= 3,
              'penultimate held >=2 s': lambda r: pen_duration(r) >= 2, 'penultimate held <2 s': lambda r: pen_duration(r) < 2}
    for qn in ('pos', 'order'):
        L += [f'## {qn}', '', '| split | D | n (per model) | image-only | native | image-only − native [95% CI] | P(pen|native wrong) − P(pen|img wrong) [95% CI] |', '|---|---|---|---|---|---|---|']
        for sn, sel in splits.items():
            for dk in ('0.5', 'full'):
                A = [rows(Rm, qn, dk, sel) for Rm in R.values()]
                if not all(len(a) for a in A):
                    continue
                a = np.concatenate(A)
                L.append(f'| {sn} | {dk} | {len(A[0])} | {a[:, 0].mean():.2f} | {a[:, 1].mean():.2f} | {f(boot(A, gap))} | {f(boot(A, pen_err))} |')
        L.append('')
    L += ['## per model (position, D=0.5)', '', '| model | image-only | native | gap | gap, penultimate held ≥2 s |', '|---|---|---|---|---|']
    for m, Rm in R.items():
        a, b = rows(Rm, 'pos', '0.5'), rows(Rm, 'pos', '0.5', splits['penultimate held >=2 s'])
        L.append(f'| {m} | {a[:, 0].mean():.2f} | {a[:, 1].mean():.2f} | {(a[:, 0] - a[:, 1]).mean():+.2f} | {(b[:, 0] - b[:, 1]).mean():+.2f} (n={len(b)}) |')
    (B / 'real4_summary.md').write_text('\n'.join(L) + '\n')
    print('\n'.join(L))


if __name__ == '__main__':
    main()
