"""Addendum AF analysis: frozen (last frame repeated, video path) vs native and image-only on the AE questions."""
import json
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
B = ROOT / 'outputs/tracking_algo_v1'
MODELS = ['qwen3vl8b', 'qwen3vl32b', 'qwen35_9b', 'internvl35_8b', 'llava_ov7b', 'gemma3_12b']
NB = 10000
rng = np.random.default_rng(20261001)


def rows(m, qn, dk):
    """Per item: correct (img, native, frozen), penultimate (img, native, frozen)."""
    R4 = {r['id']: r for r in map(json.loads, open(B / f'real4_{m}.jsonl'))}
    out = []
    for f in map(json.loads, open(B / f'real5_{m}.jsonl')):
        r = R4[f['id']]
        if qn not in r:
            continue
        q = r[qn]; a = (q[dk][0], q[dk][1], f[qn][dk])
        out.append([x == q['gt'] for x in a] + [x == q['stale'] for x in a])
    return np.array(out, float).reshape(-1, 6)


def boot(A, stat):
    v = stat(A)
    bs = [stat([a[rng.integers(0, len(a), len(a))] for a in A]) for _ in range(NB)]
    return v, float(np.quantile(bs, .025)), float(np.quantile(bs, .975))


def gap(i, j):
    return lambda A: float(np.mean([(a[:, i] - a[:, j]).mean() for a in A]))


def pen_err(A):
    a = np.concatenate(A); nw, fw = 1 - a[:, 1], 1 - a[:, 2]
    return float((a[:, 4] * nw).sum() / max(nw.sum(), 1) - (a[:, 5] * fw).sum() / max(fw.sum(), 1))


def main():
    ms = [m for m in MODELS if (B / f'real5_{m}.jsonl').exists()]
    f = lambda t: f'{t[0]:+.3f} [{t[1]:+.3f}, {t[2]:+.3f}]'
    L = ['# Addendum AF (generated by scripts/tracking_algo_real5_stats.py)', '', f'models: {ms}', '',
         '| question | D | image-only | frozen | native | frozen − native (history) | image-only − frozen (pipeline) | P(pen|native wrong) − P(pen|frozen wrong) |',
         '|---|---|---|---|---|---|---|---|']
    for qn in ('pos', 'order'):
        for dk in ('0.5', 'full'):
            A = [rows(m, qn, dk) for m in ms]
            a = np.concatenate(A)
            L.append(f'| {qn} | {dk} | {a[:, 0].mean():.2f} | {a[:, 2].mean():.2f} | {a[:, 1].mean():.2f} | {f(boot(A, gap(2, 1)))} | {f(boot(A, gap(0, 2)))} | {f(boot(A, pen_err))} |')
    L += ['', '## per model (position, D=0.5)', '', '| model | n | image-only | frozen | native | P(pen) frozen | P(pen) native |', '|---|---|---|---|---|---|---|']
    for m in ms:
        a = rows(m, 'pos', '0.5')
        L.append(f'| {m} | {len(a)} | {a[:, 0].mean():.2f} | {a[:, 2].mean():.2f} | {a[:, 1].mean():.2f} | {a[:, 5].mean():.2f} | {a[:, 4].mean():.2f} |')
    (B / 'real5_summary.md').write_text('\n'.join(L) + '\n')
    print('\n'.join(L))


if __name__ == '__main__':
    main()
