#!/usr/bin/env python3
"""Write the final hand-off report from completed offline next-stage artifacts."""
import argparse,json
from pathlib import Path
import pandas as pd
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--out",type=Path,default=Path("outputs/vetbench/next_stage_total_report_v1"));a=ap.parse_args();a.out.mkdir(parents=True,exist_ok=True)
 root=Path("outputs/vetbench/next_stage_recursive_gate_v1");rec=json.loads((root/"recursive_summary.json").read_text());gate=json.loads((root/"validation_gate_summary.json").read_text());cfg=json.loads((root/"frozen_gate_config.json").read_text());d=pd.read_csv("outputs/vetbench/recursive_state_recovery_v1/recursive_state_results.csv"); multi=json.loads(Path("outputs/vetbench/multi_position_delta_rescue_v1/multi_position_summary.json").read_text())
 ev={str(t):float(d[d.t==t].event_correct.mean()) for t in range(1,6)};evall=float(d.event_correct.mean())
 def f(x):return "NA" if x["mean"] is None else f"{x['mean']:.3f} [{x['ci95'][0]:.3f}, {x['ci95'][1]:.3f}]"
 lines=["# StateRev-VL next-stage experiment report","","## Scope and reproducibility","","This report uses the existing 250-prefix controlled-8fps event-probability cache and original native state logits; no input process was recreated and no model forward was required for recursive recovery or gate evaluation. Threshold selection is discovery-only (30 trajectories); validation is the held-out 20 trajectories. Rates and intervals aggregate prefixes within trajectory, then use trajectory-cluster bootstrap/sign permutation.","","## 1. Recursive state recovery","", "| method | overall | t>=2 | t>=3 | t1 | t2 | t3 | t4 | t5 |","|---|---:|---:|---:|---:|---:|---:|---:|---:|"]
 for m,q in rec["methods"].items():lines.append("| "+m+" | "+" | ".join(f(q[k]) for k in ("overall","t_ge2","t_ge3","t1","t2","t3","t4","t5"))+" |")
 lines += ["",f"Event argmax accuracy is {evall:.3f} overall (t1..t5: "+", ".join(f"{k}={v:.3f}" for k,v in ev.items())+"). This is substantially higher than native state accuracy (0.324), while probabilistic recursive composition reaches 0.592 overall and 0.460 at t>=3. Thus the primary deficit is state maintenance/composition, not first-step event recognition; however, recursion does accumulate event errors: probability recursion has error 0.558 conditional on a prior recursive error versus 0.488 after a prior correct step.","","## 2. Frozen validation correction gates","",f"The selected no-leakage gate is confidence >= {cfg['selected']['recursive_confidence_threshold']:.2f}, observable native top-2 margin <= {cfg['selected']['native_top2_margin_threshold']:.2f}, and native/recursive disagreement. It was selected in discovery with net gain {cfg['selected']['discovery_net_gain']:.3f} and C→W 0.000.","","| mode | accuracy | trigger | wrong→correct | correct→wrong | net gain |","|---|---:|---:|---:|---:|---:|"]
 for m,q in gate["modes"].items():
  z=q["overall"];lines.append(f"| {m} | {f(z['correct'])} | {f(z['trigger_rate'])} | {f(z['wrong_to_correct'])} | {f(z['correct_to_wrong'])} | {f(z['net_gain'])} |")
 lines += ["", "Answer: a direct disagreement switch lifts validation accuracy to 0.640 but incurs 0.080 correct→wrong, so it does not satisfy a low-harm rescue claim. The discovery-frozen low-harm gate has zero observed C→W but only 0.020 trigger/net gain. Therefore it does not yet improve repair coverage at low risk. The historical gate was re-evaluated only as an observable-margin proxy because its former GT-margin trigger leaked labels; it is not treated as a valid deployable baseline.","","The coverage-risk and trigger-rate/net-gain curve is `../next_stage_recursive_gate_v1/validation_coverage_risk_and_gain.png` with raw points in the adjacent CSV.","","## 3. Equal-budget multi-position intervention","","All 8 GPU shards completed and passed coverage plus no-op/self-patch checks: 97 target prefixes, 582 rows, maximum sanity error 0. The total residual-delta budget was fixed at 1.0 and divided equally across residual positions; Head0+L32 used frozen Head0 interpolation alpha=0.5. Statistics are trajectory-clustered.","","| condition | subset | accuracy | wrong→correct | correct→wrong | GT-margin Δ |","|---|---|---:|---:|---:|---:|"]
 effects=pd.DataFrame(multi["effects"])
 def mf(c,t,k):
  x=effects[(effects.condition==c)&(effects.subset==t)&(effects.metric==k)].iloc[0]
  return "NA" if x["mean"] is None else f"{x['mean']:.3f} [{x['ci95'][0]:.3f},{x['ci95'][1]:.3f}]"
 for c in ("baseline","L24","L32","L24_L32","Head0_L32","L24_L28_L32"):
  for t in ("overall","t_ge2","t_ge3"):
   lines.append(f"| {c} | {t} | {mf(c,t,'patched_correct')} | {mf(c,t,'wrong_to_correct')} | {mf(c,t,'correct_to_wrong')} | {mf(c,t,'delta_gt_margin')} |")
 lines += ["","Paired comparisons against L32 show L24+L32 accuracy Δ = +0.010 overall, +0.013 at t>=2, and +0.017 at t>=3; all intervals include zero. Its GT-margin difference is negative (-0.100 overall, -0.121 at t>=2), also with intervals crossing zero. L24+L28+L32 has the same categorical pattern and no significant margin advantage. Head0+L32 is categorically identical to L32. Thus multiple weak residual positions show a small lower-harm / slightly higher-accuracy trend, but do not establish superiority over single L32.","","## Answers","","1. Probabilistic recursive event accumulation reaches 0.592 overall, 0.515 at t>=2, and 0.460 at t>=3 (hard recursion: 0.552/0.460/0.400).","2. Yes, the evidence points mainly to state maintenance/composition: event accuracy is high relative to native state, and recursive composition sharply improves state accuracy; later-step decay still shows compounding event error matters.","3. No, not yet: the low-harm frozen gate has 2% trigger and +2% net gain, whereas substantially higher coverage brings measurable harm.","4. No robust superiority: L24+L32 and L24+L28+L32 reach 0.497 vs L32 0.487 overall, with lower observed correct→wrong (0.029 vs 0.059 conditional rate), but paired intervals include zero and wrong→correct is unchanged. Head0+L32 is identical to L32.","5. The best next route is calibrated state-belief correction with a discovery-fitted abstention/risk model, while retaining distributed weak deltas as a conservative intervention candidate. Do not expand layer-combination or strength searches on this dataset without a new held-out split.","","## Artifacts","","- `outputs/vetbench/next_stage_recursive_gate_v1/`: recursive/gate results and coverage-risk curve.","- `outputs/vetbench/multi_position_delta_rescue_v1/`: merged multi-position rows, summary, paired contrasts, and report.","- `outputs/vetbench/next_stage_total_report_v1/`: this report."]
 (a.out/"NEXT_STAGE_TOTAL_REPORT.md").write_text("\n".join(lines)+"\n");(a.out/"report_metadata.json").write_text(json.dumps({"offline_complete":True,"multi_position_forward_complete":False,"blocker":"NVIDIA driver unavailable on current host"},indent=2)+"\n")
 print(a.out/"NEXT_STAGE_TOTAL_REPORT.md")
if __name__=="__main__":main()
